from pathlib import Path
s = Path("board/HASHMARK.html").read_text(encoding="utf-8", errors="replace")
s = s.replace("SIM_N: 150000,", "SIM_N: 20000,")
s = s.replace("const n = (LIVE.SIM_N || 150000);", "const n = Math.min(20000, LIVE.SIM_N || 20000);")
s = s.replace("if (!fromFile && typeof liveRefresh === \"function\") {", "if (false && !fromFile && typeof liveRefresh === \"function\") {")
s = s.replace("if (typeof attachWeather === \"function\") doWx();", "setStamp(\"Board ready \u00b7 tap Refresh for live weather\", true);")
s = s.replace("const $ = (sel, root = document) => root.querySelector(sel);", "const $ = (sel, root = document) => { const el = root.querySelector(sel); return el || { style:{}, classList:{toggle(){},add(){},remove(){}}, addEventListener(){}, textContent:\"\", innerHTML:\"\", value:\"\" }; };")
s = s.replace(".overlay {", ".overlay { pointer-events: none;")
s = s.replace(".overlay.show { display: flex; }", ".overlay.show { display: flex; pointer-events: auto; }")
Path("site").mkdir(exist_ok=True)
Path("site/index.html").write_text(s)
Path("index.html").write_text(s)
print("ok", len(s))
